language: node_js
node_js:
  - "4"
  
env:
  global:
  - alias typings=./node_modules/.bin/typings
  - alias tsc=./node_modules/.bin/tsc
  
install:
  - npm install && typings install

script:
  - npm test