language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
env:
  global:
  - alias typings=./node_modules/.bin/typings
  - alias tsc=./node_modules/.bin/tsc
  
install:
  - npm install && typings install

script:
  - npm test
  
after_success:
  - npm run semantic-release